import type { Metadata } from "next";

import "./globals.css";
import "@/src/app/styles/index.scss";

import AppHeader from "@/src/widgets/AppHeader/AppHeader";
import AppFooter from "@/src/widgets/AppFooter/AppFooter";

export const metadata: Metadata = {
  title: "500na700",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppHeader />
        <main className="main">{children}</main>
        <AppFooter />
      </body>
    </html>
  );
}
